version: 0.0
os: linux
files:
  - source: / # Everything in the source directory
    destination: /home/ubuntu/NodeJsProjectCMS # Destination path
hooks:
  BeforeInstall:
    - location: deploy/application_start.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: ubuntu
