version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Specify your Node.js version
    commands:
      - echo "Installing dependencies"
      - npm install # Install dependencies for the build environment
artifacts:
  files:
    - '**/*' # Include all files in the artifact
    - appspec.yml # Ensure appspec.yml is included in the artifact
    - deploy/** # Include the deploy folder (scripts, etc.)
