version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t my-node-app .
      - run:
          name: Run container
          command: docker run -p 5000:5000 my-node-app

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
