version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  version: 2
  build-only:
    jobs:
      - build
