apiVersion: v1
kind: PersistentVolume
metadata:
  name: existing-ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-0743c5f74a4638329
    fsType: ext4
