apiVersion: v1
kind: PersistentVolume
metadata:
  name: existing-ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  awsElasticBlockStore:
    volumeID: vol-05158e76b55802e69
    fsType: ext4
