# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ebs-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: gp2 # or gp3, depending on your EKS setup
#   resources:
#     requests:
#       storage: 10Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: existing-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
