apiVersion: apps/v1
kind: Deployment
metadata:
  name: newblog-deployment
  labels:
    app: newblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newblog
  template:
    metadata:
      labels:
        app: newblog
    spec:
      containers:
      - name: newblog
        image: mammarraza/newblog:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URL
          value: mongodb+srv://20ntucs1120:WU6TAoQiyFljPJxO@blog-cluster.bvblv9k.mongodb.net/blog
