pipeline:
  name: MyAppPipeline
  identifier: MyAppPipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubconnection
        build: <+input>
  stages:
    - stage:
        name: node-installation-build
        identifier: nodeinstallationbuild
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: vm-pool
                harnessImageConnectorRef: account.harnessImage
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec: {}
